name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      id: cache
      with:
        path: /home/runner/.cargo/bin/wasm-pack
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: cargo install wasm-pack
    - name: Build
      run: wasm-pack build --target web
    - name: Archive build
      uses: actions/upload-artifact@v4
      with:
        name: wasmgl-build
        path: |
          ./pkg/